name: Build Workflow
on:
  sh:
    branches:
      - main # Atau ganti dengan nama branch yang ingin Anda pantau

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: imagemagick
        run: sudo apt install imagemagick -y

      - name: wget
        run: sudo apt install wget

      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt-get install -y ffmpeg

      - name: Install Ely
        run: npm install

      - name: Run Ely
        run: node index.js